In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import seaborn as sns
%matplotlib inline

In [2]:
wuhan = pd.read_csv("Wuhan/output_data/wuhan_summary_data.csv")
wuhan = wuhan.set_index("Month")
wuhan

,Avg pm2.5_18,Avg AQI_18,Max pm2.5_18,Max AQI_18,Min pm2.5_18,Min AQI_18,Avg pm2.5_19,Avg AQI_19,Max pm2.5_19,Max AQI_19,Min pm2.5_19,Min AQI_19,Avg pm2.5_20,Avg AQI_20,Max pm2.5_20,Max AQI_20,Min pm2.5_20,Min AQI_20
Month,,,,,,,,,,,,,,,,,,
1,179.466667,231.720000,255.0,305.5,117.0,182.7,180.166667,232.173333,248.0,297.6,116.0,182.2,146.000000,203.723333,194.0,244.1,70.0,158.5
2,155.785714,210.535714,205.0,255.0,82.0,164.7,153.555556,208.066667,195.0,245.1,78.0,162.6,122.689655,187.775862,184.0,234.2,66.0,156.4
3,142.580645,198.248387,175.0,225.3,95.0,171.4,145.129032,200.274194,185.0,235.2,99.0,173.4,119.870968,184.509677,157.0,207.4,59.0,152.8
4,146.933333,203.306667,227.0,276.8,79.0,163.1,126.000000,187.823333,161.0,211.4,65.0,155.9,113.100000,180.300000,156.0,206.5,47.0,129.3
5,120.677419,185.454839,166.0,216.4,66.0,156.4,125.516129,187.783871,162.0,212.4,64.0,155.4,118.225806,183.493548,158.0,208.4,72.0,159.5
6,113.448276,181.168966,158.0,208.4,67.0,156.9,111.103448,179.675862,148.0,198.7,57.0,151.8,84.100000,165.750000,133.0,191.0,56.0,151.3
7,97.750000,172.145833,132.0,190.5,48.0,131.8,102.541667,175.262500,138.0,193.6,74.0,160.5,78.833333,157.370833,145.0,197.2,29.0,86.5

In [3]:
rome= pd.read_csv("Guido/output_data/guido_summary_data.csv")
rome = rome.set_index("Month")
rome

,Avg pm2.5_18,Avg AQI_18,Max pm2.5_18,Max AQI_18,Min pm2.5_18,Min AQI_18,Avg pm2.5_19,Avg AQI_19,Max pm2.5_19,Max AQI_19,Min pm2.5_19,Min AQI_19,Avg pm2.5_20,Avg AQI_20,Max pm2.5_20,Max AQI_20,Min pm2.5_20,Min AQI_20
Month,,,,,,,,,,,,,,,,,,
1,47.800000,120.500000,87.0,167.2,17.0,61.3,46.551724,121.320690,91.0,169.3,21.0,69.7,66.666667,146.510000,97.0,172.4,25.0,78.1
2,45.250000,118.864286,87.0,167.2,25.0,78.1,52.259259,125.414815,95.0,171.4,13.0,52.9,50.307692,130.800000,82.0,164.7,17.0,61.3
3,35.451613,100.219355,72.0,159.5,13.0,52.9,44.655172,122.224138,68.0,157.4,25.0,78.1,47.400000,120.946667,85.0,166.2,17.0,61.3
4,45.866667,124.256667,72.0,159.5,21.0,69.7,46.137931,121.093103,82.0,164.7,17.0,61.3,49.500000,127.053846,78.0,162.6,17.0,61.3
5,38.290323,107.000000,76.0,161.6,17.0,61.3,27.935484,84.764516,46.0,126.9,13.0,52.9,38.433333,107.833333,61.0,153.8,21.0,69.7
6,38.357143,108.360714,53.0,144.1,25.0,78.1,54.100000,141.433333,78.0,162.6,25.0,78.1,30.000000,89.063333,42.0,117.0,21.0,69.7
7,49.333333,131.733333,72.0,159.5,34.0,97.1,48.375000,130.854167,63.0,154.9,34.0,97.1,34.391304,97.534783,76.0,161.6,9.0,37.5

In [4]:
stockholm = pd.read_csv("Stockholm/output_data/stockholm_summary_data.csv")
stockholm = stockholm.set_index("Month")
stockholm

,Avg pm2.5_18,Avg AQI_18,Max pm2.5_18,Max AQI_18,Min pm2.5_18,Min AQI_18,Avg pm2.5_19,Avg AQI_19,Max pm2.5_19,Max AQI_19,Min pm2.5_19,Min AQI_19,Avg pm2.5_20,Avg AQI_20,Max pm2.5_20,Max AQI_20,Min pm2.5_20,Min AQI_20
Month,,,,,,,,,,,,,,,,,,
1,27.466667,84.100000,58.0,152.3,9.0,37.5,25.933333,79.716667,65.0,155.9,9.0,37.5,23.400000,75.056667,47.0,129.3,10.0,41.7
2,29.821429,89.375000,50.0,136.7,9.0,37.5,37.607143,106.160714,64.0,155.4,23.0,73.9,19.137931,65.079310,40.0,112.1,7.0,29.2
3,41.354839,114.922581,63.0,154.9,20.0,67.6,26.741935,82.041935,46.0,126.9,10.0,41.7,27.258065,83.838710,61.0,153.8,11.0,45.8
4,41.266667,112.823333,74.0,160.5,17.0,61.3,48.633333,122.110000,100.0,174.0,21.0,69.7,18.166667,62.866667,57.0,151.8,8.0,33.3
5,38.516129,108.261290,66.0,156.4,18.0,63.4,30.161290,90.400000,59.0,152.8,13.0,52.9,16.774194,59.332258,29.0,86.5,7.0,29.2
6,22.222222,72.044444,40.0,112.1,9.0,37.5,27.633333,84.306667,61.0,153.8,11.0,45.8,23.866667,75.536667,40.0,112.1,8.0,33.3
7,30.166667,89.858333,53.0,144.1,9.0,37.5,19.416667,65.750000,37.0,104.7,9.0,37.5,14.083333,52.050000,27.0,82.3,6.0,25.0

In [5]:
melbourne = pd.read_csv("Melbourne/output_data/melbourne_summary_data.csv")
melbourne = melbourne.set_index("Month")
melbourne

,Avg pm2.5_18,Avg AQI_18,Max pm2.5_18,Max AQI_18,Min pm2.5_18,Min AQI_18,Avg pm2.5_19,Avg AQI_19,Max pm2.5_19,Max AQI_19,Min pm2.5_19,Min AQI_19,Avg pm2.5_20,Avg AQI_20,Max pm2.5_20,Max AQI_20,Min pm2.5_20,Min AQI_20
Month,,,,,,,,,,,,,,,,,,
1,38.300000,107.273333,65,155.9,21,69.7,37.000000,105.417241,65,155.9,13,52.9,59.433333,124.840000,272,322.3,18,63.4
2,33.076923,95.919231,64,155.4,18,63.4,35.666667,101.962963,65,155.9,19,65.5,34.821429,95.721429,106,177.0,16,59.2
3,30.516129,90.241935,49,134.2,18,63.4,35.200000,100.780000,68,157.4,17,61.3,23.535714,74.928571,35,99.2,11,45.8
4,44.866667,114.256667,113,180.7,18,63.4,27.185185,82.755556,59,152.8,4,16.7,24.966667,77.800000,44,121.9,4,16.7
5,38.100000,104.746667,83,165.2,21,69.7,24.366667,75.826667,69,158.0,8,33.3,26.612903,81.393548,66,156.4,11,45.8
6,42.900000,112.986667,104,176.0,14,55.0,29.400000,87.480000,71,159.0,15,57.1,36.833333,100.640000,120,184.3,11,45.8
7,28.956522,86.073913,67,156.9,9,37.5,24.583333,76.462500,75,161.1,9,37.5,26.782609,82.743478,49,134.2,13,52.9

In [8]:
wgsm_summary = pd.concat([wuhan,rome,stockholm,melbourne], axis=0,keys=['Wuhan','Rome','Stockholm','Melbourne'])
wgsm_summary

                 Avg pm2.5_18  Avg AQI_18  Max pm2.5_18  Max AQI_18  \
          Month
Wuhan     1        179.466667  231.720000         255.0       305.5
          2        155.785714  210.535714         205.0       255.0
          3        142.580645  198.248387         175.0       225.3
          4        146.933333  203.306667         227.0       276.8
          5        120.677419  185.454839         166.0       216.4
          6        113.448276  181.168966         158.0       208.4
          7         97.750000  172.145833         132.0       190.5
Rome      1         47.800000  120.500000          87.0       167.2
          2         45.250000  118.864286          87.0       167.2
          3         35.451613  100.219355          72.0       159.5
          4         45.866667  124.256667          72.0       159.5
          5         38.290323  107.000000          76.0       161.6
          6         38.357143  108.360714          53.0       144.1
          7         49.333333  131.733333          72.0       159.5
Stockholm 1         27.466667   84.100000          58.0       152.3
          2         29.821429   89.375000          50.0       136.7
          3         41.354839  114.922581          63.0       154.9
          4         41.266667  112.823333          74.0       160.5
          5         38.516129  108.261290          66.0       156.4
          6         22.222222   72.044444          40.0       112.1
          7         30.166667   89.858333          53.0       144.1
Melbourne 1         38.300000  107.273333          65.0       155.9
          2         33.076923   95.919231          64.0       155.4
          3         30.516129   90.241935          49.0       134.2
          4         44.866667  114.256667         113.0       180.7
          5         38.100000  104.746667          83.0       165.2
          6         42.900000  112.986667         104.0       176.0
          7         28.956522   86.073913          67.0       156.9

                 Min pm2.5_18  Min AQI_18  Avg pm2.5_19  Avg AQI_19  \
          Month
Wuhan     1             117.0       182.7    180.166667  232.173333
          2              82.0       164.7    153.555556  208.066667
          3              95.0       171.4    145.129032  200.274194
          4              79.0       163.1    126.000000  187.823333
          5              66.0       156.4    125.516129  187.783871
          6              67.0       156.9    111.103448  179.675862
          7              48.0       131.8    102.541667  175.262500
Rome      1              17.0        61.3     46.551724  121.320690
          2              25.0        78.1     52.259259  125.414815
          3              13.0        52.9     44.655172  122.224138
          4              21.0        69.7     46.137931  121.093103
          5              17.0        61.3     27.935484   84.764516
          6              25.0        78.1     54.100000  141.433333
          7              34.0        97.1     48.375000  130.854167
Stockholm 1               9.0        37.5     25.933333   79.716667
          2               9.0        37.5     37.607143  106.160714
          3              20.0        67.6     26.741935   82.041935
          4              17.0        61.3     48.633333  122.110000
          5              18.0        63.4     30.161290   90.400000
          6               9.0        37.5     27.633333   84.306667
          7               9.0        37.5     19.416667   65.750000
Melbourne 1              21.0        69.7     37.000000  105.417241
          2              18.0        63.4     35.666667  101.962963
          3              18.0        63.4     35.200000  100.780000
          4              18.0        63.4     27.185185   82.755556
          5              21.0        69.7     24.366667   75.826667
          6              14.0        55.0     29.400000   87.480000
          7               9.0        37.5     24.583333   76.462500

                 Max pm2.5_19  Max AQI_19  Min pm2.5_19  Min AQI_19  \
          Month
Wuhan     1             248.0       297.6         116.0       182.2
          2             195.0       245.1          78.0       162.6
          3             185.0       235.2          99.0       173.4
          4             161.0       211.4          65.0       155.9
          5             162.0       212.4          64.0       155.4
          6             148.0       198.7          57.0       151.8
          7             138.0       193.6          74.0       160.5
Rome      1              91.0       169.3          21.0        69.7
          2              95.0       171.4          13.0        52.9
          3              68.0       157.4          25.0        78.1
          4              82.0       164.7          17.0        61.3
          5              46.0       126.9          13.0        52.9
          6              78.0       162.6          25.0        78.1
          7              63.0       154.9          34.0        97.1
Stockholm 1              65.0       155.9           9.0        37.5
          2              64.0       155.4          23.0        73.9
          3              46.0       126.9          10.0        41.7
          4             100.0       174.0          21.0        69.7
          5              59.0       152.8          13.0        52.9
          6              61.0       153.8          11.0        45.8
          7              37.0       104.7           9.0        37.5
Melbourne 1              65.0       155.9          13.0        52.9
          2              65.0       155.9          19.0        65.5
          3              68.0       157.4          17.0        61.3
          4              59.0       152.8           4.0        16.7
          5              69.0       158.0           8.0        33.3
          6              71.0       159.0          15.0        57.1
          7              75.0       161.1           9.0        37.5

                 Avg pm2.5_20  Avg AQI_20  Max pm2.5_20  Max AQI_20  \
          Month
Wuhan     1        146.000000  203.723333         194.0       244.1
          2        122.689655  187.775862         184.0       234.2
          3        119.870968  184.509677         157.0       207.4
          4        113.100000  180.300000         156.0       206.5
          5        118.225806  183.493548         158.0       208.4
          6         84.100000  165.750000         133.0       191.0
          7         78.833333  157.370833         145.0       197.2
Rome      1         66.666667  146.510000          97.0       172.4
          2         50.307692  130.800000          82.0       164.7
          3         47.400000  120.946667          85.0       166.2
          4         49.500000  127.053846          78.0       162.6
          5         38.433333  107.833333          61.0       153.8
          6         30.000000   89.063333          42.0       117.0
          7         34.391304   97.534783          76.0       161.6
Stockholm 1         23.400000   75.056667          47.0       129.3
          2         19.137931   65.079310          40.0       112.1
          3         27.258065   83.838710          61.0       153.8
          4         18.166667   62.866667          57.0       151.8
          5         16.774194   59.332258          29.0        86.5
          6         23.866667   75.536667          40.0       112.1
          7         14.083333   52.050000          27.0        82.3
Melbourne 1         59.433333  124.840000         272.0       322.3
          2         34.821429   95.721429         106.0       177.0
          3         23.535714   74.928571          35.0        99.2
          4         24.966667   77.800000          44.0       121.9
          5         26.612903   81.393548          66.0       156.4
          6         36.833333  100.640000         120.0       184.3
          7         26.782609   82.743478          49.0       134.2

                 Min pm2.5_20  Min AQI_20
          Month
Wuhan     1              70.0       158.5
          2              66.0       156.4
          3              59.0       152.8
          4              47.0       129.3
          5              72.0       159.5
          6              56.0       151.3
          7              29.0        86.5
Rome      1              25.0        78.1
          2              17.0        61.3
          3              17.0        61.3
          4              17.0        61.3
          5              21.0        69.7
          6              21.0        69.7
          7               9.0        37.5
Stockholm 1              10.0        41.7
          2               7.0        29.2
          3              11.0        45.8
          4               8.0        33.3
          5               7.0        29.2
          6               8.0        33.3
          7               6.0        25.0
Melbourne 1              18.0        63.4
          2              16.0        59.2
          3              11.0        45.8
          4               4.0        16.7
          5              11.0        45.8
          6              11.0        45.8
          7              13.0        52.9

In [9]:
wgsm_summary.to_csv("city_summary_data_results.csv")

### Working on plotting- not complete yet

In [11]:
# import seaborn as sns

In [1]:
# corr = wgsm_summary[["Avg AQI_18","Avg AQI_19","Avg AQI_20"]].corr()
# ax = sns.heatmap(corr,vmin=-1,vmax=1, center=0, cmap=sns.diverging_palette(20, 220,n=200),square=True)
# ax.set_xticklabels(ax.get_xticklabels(),rotation=45,horizontalalignment='right')
# #compare for death of covid